### ISSUE TITLE
cannot find magic_enum.hpp

### ISSUE THREAD

**Issue by daeho-ro** [Loki-Astari/ThorsSerializer#1]
**Is your feature request related to a problem? Please describe.**
During build, magic_enum.hpp is not found, because of magic_enum changes the library path within a version v0.9.7.
See here, 
- https://github.com/Neargye/magic_enum/pull/374/files#diff-ea13c4b53c26f8e963a64f40a86710bacc1e1097ef024f6e2b2391ffcbb9d262

**Describe the solution you'd like**
Can you add a prefix for the header such as
```
magic_enum/magic_enum.hpp
```

**Describe alternatives you've considered**
I may replace the string but I want to let you know the changes.

**Additional context**

**Comment by Loki-Astari** [comment]
Checking.

**Comment by Loki-Astari** [comment]
The current documentation of magic enum still indicates to use
```
#include <magic_enum.hpp>
```
See: https://github.com/Neargye/magic_enum/blob/master/doc/reference.md

The configuration script also allows you to specify the location where magic_enum can be found.

```
./configure --with-magicenum-header-only-root=<location where the "magic_enum.hpp" can be found>
```

I also checked that `brew` still installs magic_enum directly into the include directory (not inside a subdirectory). If I changed the current code it would break existing implementations.

**Comment by daeho-ro** [comment]
OK, I will try. This is also related to the homebrew upgrade.
- https://github.com/Homebrew/homebrew-core/pull/197646

**Comment by Loki-Astari** [comment]
I will work on a fix that tries to compensate for potentially both locations this weekend.

**Comment by Loki-Astari** [comment]
Ahhh. I see. My code is blocking magic_enum from being pushed in homebrew.
Let me look at that.

**Comment by Loki-Astari** [comment]
Resolved with https://github.com/Homebrew/homebrew-core/pull/197897
