### ISSUE TITLE
Header-only branch missing

### ISSUE THREAD

**Issue by mjkl-gh** [Loki-Astari/ThorsSerializer#1]
Dear @Loki-Astari 

I noticed some stuff got moved around with the Thorsserializer repo. And i think something went wrong there.

Currently the `header-only` branch is missing from this repo, but it's stil mentioned at https://github.com/Loki-Astari/ThorsSerializer/tree/master?tab=readme-ov-file#header-only

Can it be re-added?

**Comment by Loki-Astari** [comment]
Sorry the location changes:

> git clone --single-branch --branch header-only https://github.com/Loki-Astari/ThorsMongo.git


Notice: The name of the repository is now: "ThorsMongo" but contains the same things as before.
