### ISSUE TITLE
How to make traits for a template

### ISSUE THREAD

**Issue by byzhang** [Loki-Astari/ThorsSerializer#15]
Suppose I have such a struct
```
namespace n {
template <typename R>
struct RR {
  std::string msg;
  std::vector<R> vec_R;
};
```
How should I ThorsAnvil_MakeTrait it?
I tried the simplest one
```
ThorsAnvil_MakeTrait(n::RR, msg, vec_R);
```
But it failed without surprise.

**Comment by Loki-Astari** [comment]
I have not done the work for template types.

You will have to declare a trait for each specialization.

    ThorsAnvil_MakeTrait(n::RR<int>, msg, vec_R);
    ThorsAnvil_MakeTrait(n::RR<float>, msg, vec_R);
    ... etc

I don't have time to look at this week (I am out at a conference)
But I can have a look next week (if this is still something you need).

**Comment by byzhang** [comment]
Apperciate it!
2015年9月20日 18:28，"Loki Astari" <notifications@github.com>写道：

**Comment by Loki-Astari** [comment]
I have fixed this.
You can now specify a template type explicitly.

     ThorsAnvil_Template_MakeTrait(1, n::RR, msg, vec_R);
