### ISSUE TITLE
How can I build static library ?

### ISSUE THREAD

**Issue by nRewik** [Loki-Astari/ThorsSerializer#17]
I see an option `--enable-static` in `.configure`. I want to build static library for `ThorsSerializer`. I've set the flag, but nothing happen. It still build dynamic library for me. 

Does `ThorsSerializer` support making static library?

**Comment by Loki-Astari** [comment]
Sorry.
Not directly from the ".configuration"

But if you look at the Makefile.


Change:
TARGET▸ ▸   ▸   ▸   ▸   ▸   = ThorSerialize.slib

To:
TARGET▸ ▸   ▸   ▸   ▸   ▸   = ThorSerialize.a

That should be the only changes you need to make.



On Fri, Feb 19, 2016 at 2:53 AM, Nutchaphon Rewik <notifications@github.com>
wrote:

> I see an option --enable-static in .configure. I want to build static
> library for ThorsSerializer. I've set the flag, but nothing happen. It
> still build dynamic library for me.
>
> Does ThorsSerializer support making static library?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Loki-Astari/ThorsSerializer/issues/17>.
>



-- 
See my vizify profile!
[image: Loki Astari's Visual Thumbprint]
<https://www.vizify.com/es/5245501d6d15e200070007a5>

**Comment by nRewik** [comment]
I have set `TARGET  = ThorSerialize.a`. This is the log from running `make`.

```
End Installing Headers
/Applications/Xcode.app/Contents/Developer/usr/bin/make -j8 VERBOSE=NONE PREFIX=/Users/nRewik/Developer/ThorsSerializer/build CXXSTDVER=14 TARGET_MODE=debug INSTALL_ACTIVE= all
Building debug
ar rv debug/libThorSerialize.a                                       OK
 Done Building Serialize debug/libThorSerialize.a
Done
rm debug/libThorSerialize.a
/Applications/Xcode.app/Contents/Developer/usr/bin/make VERBOSE=NONE PREFIX=/Users/nRewik/Developer/ThorsSerializer/build CXXSTDVER=14 TARGET_MODE=debug doInstall
Start Installing Applications
End Installing Applications
Start Installing Libraries
End Installing Libraries
cp: debug/libThorSerialize.a: No such file or directory
make[3]: *** [install_static_lib_ThorSerialize] Error 1
make[2]: *** [install_Dodebug] Error 2
make[1]: *** [Serialize.dir] Error 2
make: *** [src.dir] Error 2
```

**Comment by martin-seomoz** [comment]
That's inconvenient.
I'll try and have a look later this week and post a fix.

Loki

**Comment by Loki-Astari** [comment]
I have updated the build system so `--enable-static` will now work as expected.
