### ISSUE TITLE
Serializing does not compile if class has static member variables

### ISSUE THREAD

**Issue by FlorianLuetticke** [Loki-Astari/ThorsSerializer#18]
Hello

I noticed, that if you have a static member in a class and try to serialize it, the program will not compile.

Is this expected?
Cheers,
Florian Luetticke
Compiler:
gcc version 4.9.1 20140922 (Red Hat 4.9.1-10) (GCC)

Minimal example:
```c++

#include "thorsSerializer/Serialize/Traits.h"
#include "thorsSerializer/Serialize/SerUtil.h"
#include "thorsSerializer/Serialize/JsonThor.h"
#include <iostream>
class test{
    static int member;
public:
    test(){}
    friend struct ThorsAnvil::Serialize::Traits<test>;
};
int test::member=3;

int main(int argc, char **argv) {
    test t1;
    using ThorsAnvil::Serialize::jsonExport;
    std::cout << jsonExport(t1) << "\n";
}
```
Compile error in the file.
[error.txt](https://github.com/Loki-Astari/ThorsSerializer/files/188298/error.txt)

**Comment by Loki-Astari** [comment]
I did not anticipate that people would want to serialize static members as they are not part of the object (they are part of the class). I will add it to me to-do list.

**Comment by FlorianLuetticke** [comment]
Thank you. 
My plan was to use static members like version or histogram_bin_size and make the receiver aware that there may be different versions.
For the time being, I will not use nonstatic members then.

**Comment by Loki-Astari** [comment]
Serializing the static members is easy.

But how do you expect to behave when you read a serialized object back in. Every object will then modify the static member (which affects all the other objects). This has implications for applications that are using multiple threads.

**Comment by Loki-Astari** [comment]
I have added the ability to serialize static members.
