### ISSUE TITLE
Does not build with MS compiler (VS2015)

### ISSUE THREAD

**Issue by marnef** [Loki-Astari/ThorsSerializer#19]
If you update to the attached file version the library can be compiled with MS compiler (VS2015). Please verify that the file is still working with the compilers you were supporting so far.

[Traits.zip](https://github.com/Loki-Astari/ThorsSerializer/files/223333/Traits.zip)

**Comment by Loki-Astari** [comment]
Hi @marnef 
I tried applying the patch file and I am not convinced it is a correct change.

You have added `NUM_ARGS_EXPAND()` which seems to do the same as `EXPAND_()`


You are using `EXPAND_()` directly on all the lines `#define REP_OF_**` I am not sure this is needed can you verify. Also macros that contain a trailing `_` are not meant to be used directly.

Then on line 85.

#define NameAction(Type, Member)        _EXPAND(Member)

I am not sure what `_EXPAND()` is doing here. Is that supposed to be `EXPAND_()`?

Next time can you please submit a "Pull Request" it makes comparing the code easier.

**Comment by marnef** [comment]
Hi Loki-Astari
Sorry, I don't know how to use git... But finally I got your code running under VS2015!
I added NUM_ARGS_EXPAND so I didn't have to move your EXPAND_ to another location in the file. But you're right, it's the same.
For the rest I'm going to do another check tomorrow morning.
Marco

**Comment by marnef** [comment]
Pull requests #23 and #24
