### ISSUE TITLE
JsonPrinter.cpp does not compile in VS2015

### ISSUE THREAD

**Issue by marnef** [Loki-Astari/ThorsSerializer#20]
Line 26, change type to 'char const** seporator' and it will work... Maybe you want to rename the variable to separator as well?

**Comment by Loki-Astari** [comment]
I am very strict on my types (as it is important in C++)
I am curious is there not a better; as your change throws away type information that can be used in static analysis.

**Comment by marnef** [comment]
Pull request #22
