### ISSUE TITLE
issue with making configuration for build

### ISSUE THREAD

**Issue by redcameron** [Loki-Astari/ThorsSerializer#30]
I'm installing ThorsSerializer and I've run into this issue when going through the installation process.  When I type 'make' after getting the library and entering './configure --disable-binary' I get the error messages as shown below.

Buiding src Start
make -C src install PREFIX=/home/mark/ThorsSerializer/build CXXSTDVER=17
make[1]: Entering directory '/home/mark/ThorsSerializer/src'
Buiding Serialize Start
make -C Serialize install PREFIX=/home/mark/ThorsSerializer/build CXXSTDVER=17
make[2]: Entering directory '/home/mark/ThorsSerializer/src/Serialize'
Building Objects for Testing and Coverage
make[3]: Entering directory '/home/mark/ThorsSerializer/src/Serialize'
ERROR
g++ -c JsonLexer.lex.cpp -o coverage/JsonLexer.lex.o -I/usr/local/include -fPIC -Wall -Wextra -Wstrict-aliasing -pedantic -Werror -Wunreachable-code -Wno-long-long -Wno-deprecated-register -Wno-sign-compare -I/home/mark/ThorsSerializer/build/include -isystem /home/mark/ThorsSerializer/build/include3rd -DCOVERAGE_Serialize -g -fprofile-arcs -ftest-coverage -DCOVERAGE_TEST -Wno-unused-private-field -Wno-unreachable-code -DTHOR_USE_CPLUSPLUS17 -std=c++17
========================================
JsonLexer.lex.cpp:1:1: error: ‘flex’ does not name a type
 flex -t JsonLexer.l
 ^
cc1plus: error: unrecognized command line option ‘-Wno-unused-private-field’ [-Werror]
cc1plus: error: unrecognized command line option ‘-Wno-deprecated-register’ [-Werror]
cc1plus: all warnings being treated as errors
/home/mark/ThorsSerializer/build/tools/Makefile:560: recipe for target 'coverage/JsonLexer.lex.o' failed
make[3]: *** [coverage/JsonLexer.lex.o] Error 1
make[3]: *** Waiting for unfinished jobs....
g++ -c Serialize.cpp -DCOVERAGE_Serialize                            OK
make[3]: *** wait: No child processes.  Stop.
/home/mark/ThorsSerializer/build/tools/Makefile:343: recipe for target 'run_test' failed
make[2]: *** [run_test] Error 2
make[2]: Leaving directory '/home/mark/ThorsSerializer/src/Serialize'
/home/mark/ThorsSerializer/build/tools/Project.Makefile:33: recipe for target 'Serialize.dir' failed
make[1]: *** [Serialize.dir] Error 2
make[1]: Leaving directory '/home/mark/ThorsSerializer/src'
/home/mark/ThorsSerializer/build/tools/Project.Makefile:33: recipe for target 'src.dir' failed
make: *** [src.dir] Error 2

Please help! It looks like a type name is missing from JsonLexer.lex.cpp.

**Comment by Loki-Astari** [comment]
> JsonLexer.lex.cpp:1:1: error: ‘flex’ does not name a type
> flex -t JsonLexer.l

Looks like you don't have `flex` installed on your system.
Which is strange as the configuration should test for that.

> cc1plus: error: unrecognized command line option ‘-Wno-unused-private-field’ [-Werror]
> cc1plus: error: unrecognized command line option ‘-Wno-deprecated-register’ [-Werror]

Your compiler does not support all the flags I use.
What version of the compiler are you using?

Can you attach.
    config.log
    config.status

**Comment by Loki-Astari** [comment]
This is an issue with the users OS not having the correct tools installed.
Since I have no further feedback in a month and no further information I am closing the issue.
