### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by abdessattar** [Loki-Astari/ThorsSerializer#32]
Dear sir,

I am Abdessattar Bahri, engineering student, in proess of setting my graduation project which is related to your repository.

I need to include this library to my project with visual studio 2015. To do this I must have the directories lib and include.
To obtain those , I have to compile this library.
May be it can be built with mingw and msys.
I tried with those tools but I can obtain the wanted result.
So i need a help.
Hwo can I compile it?

Thank you in advance,

Best regards,

**Comment by 0X1A** [comment]
@Loki-Astari Is there any recommended way of getting this lib built on Windows? Build instructions don't seem to cover it and I think you've noted in another issue that this does indeed build on Windows

**Comment by Loki-Astari** [comment]
If you install Cygwin on your windows machine the build instructions will work the same.

Unfortunately I don't have a way to test for Windows platforms.
But if you submit a pull request I will definitely consider it.

**Comment by Loki-Astari** [comment]
This now builds correctly on windows (MSYS2) (see the `.github/workflow/setup.yml` file for details.
There is also a header only version that builds on Window.
