### ISSUE TITLE
Multiple Inheritance support

### ISSUE THREAD

**Issue by vrobles-gee** [Loki-Astari/ThorsSerializer#38]
Hello. I was wondering if multiple inheritance is somehow supported. I have been using ThorsAnvil_ExpandTrait so far, but it only allows to specify one parent class, and it cannot be called twice for the same child class. If is not supported, any ideas on a workaround are really appreciated. Thanks.

**Comment by Loki-Astari** [comment]
Yes.
I just added support last weekend.
See: https://github.com/Loki-Astari/ThorsSerializer/blob/master/doc/example3.md

**Comment by Loki-Astari** [comment]
Sorry. Read that incorrectly.

**Comment by vrobles-gee** [comment]
Hello, thanks for the fast reply. 

Sure, let me elaborate a little on the issue. I have several classes (structs) to represent network connections, with this parent/child hierarchy:

- Connection
  - IPConnection
    - IPv4Connection
    - IPv6Connection
- TcpConnection
- UdpConnection

All this classes are abstract, and I use multiple inheritance to mix them and create the final ones that can really be instantiated, for example:

`struct Tcp4Connection : public IPv4Connection, public TcpConnection`

We have done this to avoid repeating fields (and logic) over an over, for example, we also have a TCP connection class for IPv6:

`struct Tcp6Connection : public IPv6Connection, public TcpConnection`

That way, once the object reaches a point of code dealing with TCP protocol, we only need to cast to TcpConnection (no matter if it is IPv4 or IPv6). 

So, the issue is that I need to serialize / deserialize classes with multiple parents like Tcp4Connection and Udp4Connection, but like I said, I can't find a way to do so. I thought of three approaches but so far none is supported or working:

1) Using ThorsAnvil_MakeTrait to specify both parents: not supported, only allows one parent
2) Calling ThorsAnvil_ExpandTrait two times for the Tcp4Connection class using each parent class: not working, it throws 'redefinition of class Tcp4Connection’ error.
3) Declaring only a trait for the final Tcp4Connection (and adding all the relevant fields of its parent classes): It won't compile, it throws 'deduced conflicting types' error.

I also checked ThorsSerializer code (Traits file) but didn't find any other idea, so I was wondering maybe multiple inheritance is not supported and decided to ask here. If it is not supported, I would like to ask if approach #3 should work (treating the class as if it was the only one and listing the parent fields).

Thanks in advance.

**Comment by Loki-Astari** [comment]
I assumed options 3 would work.
I tried it but as reported it fails. I'll take a look this weekend.

**Comment by Loki-Astari** [comment]
Opps did not mean to close.

**Comment by vrobles-gee** [comment]
Thanks. I appreciate it.

**Comment by Loki-Astari** [comment]
Sorry it took so long.
Sorted now. I have not written docs yet but you can see example [here](https://github.com/Loki-Astari/ThorsSerializer/blob/master/src/Serialize/test/Issue38Test.cpp).

Basically you need to create a type that represents all the parents.

    using ASetOfAllMyParents = ThorsAnvil::Serialize::Parents<Parent1, Parent2>;  // Allows as many parents as you need.
    // Then use `ThorsAnvil_ExpandTrait` using ASetOfAllMyParents as the parent.
    ThorsAnvil_ExpandTrait(ASetOfAllMyParents, MyType, mymember);
