### ISSUE TITLE
Optional and required values

### ISSUE THREAD

**Issue by ivohedtke** [Loki-Astari/ThorsSerializer#39]
Hi,

I would like to use your lib with the following use-case:

- JSON input can contain more values than the class has members
- Some JSON values are optional, so I use pointers in the class
- Some values are required, and I want an exception if it is missing

How do I get the behavior that

- class members that are pointers are imported as nullptr when missing in JSON
- JSON values that have no class members are ignored
- class members that are no pointers have to be present in the JSON, otherwise, an exception should be thrown

The following code has all 4 examples I consider: Is there a way to make t1, t2 and t3 work and let import into t4 throw an exception?
```c++
#include <iostream>

#include <ThorSerialize/JsonThor.h>
#include <ThorSerialize/Traits.h>

using namespace std;
using namespace ThorsAnvil::Serialize;

struct Test {
    int num;
    int* optionalNum;
    ~Test() { delete optionalNum; }
};

ThorsAnvil_MakeTrait(Test, num, optionalNum);

int main()
{
    using PT = ParserInterface::ParseType;
    Test t1, t2, t3, t4;

    // should work perfectly: works
    string twoVals = R"( {"num": 42, "optionalNum": 43} )";
    istringstream(twoVals) >> jsonImport(t1, PT::Weak);
    cout << jsonExport(t1) << endl;

    // ignoring additional values is fine: works
    string threeVals = R"( {"num": 42, "optionalNum": 43, "tooMany": 44} )";
    istringstream(threeVals) >> jsonImport(t2, PT::Weak);
    cout << jsonExport(t2) << endl;

    // non-defined pointer members are nullptr: works
    string oneVal = R"( {"num": 42} )";
    istringstream(oneVal) >> jsonImport(t3, PT::Weak);
    cout << jsonExport(t3) << endl;

    // class T has a member "num" which is missing in the JSON -> exception?
    string zeroVals = "{}";
    istringstream(zeroVals) >> jsonImport(t4, PT::Weak);
    cout << jsonExport(t4) << endl;

    return 0;
}
```

Thanks

**Comment by Loki-Astari** [comment]
I would like to use your lib with the following use-case:

- JSON input can contain more values than the class has members
        **Supported as the default behavior.**

- Some JSON values are optional, so I use pointers in the class
        **Supported as the default behavior.**

- Some values are required, and I want an exception if it is missing
        Unfortunately this is not supported. If you want to add the code I will accept a pull request.

**Comment by Loki-Astari** [comment]
How do I get the behavior that

How do I get the behavior that

- class members that are pointers are imported as nullptr when missing in JSON
    This can be done externally by creating correct constructors that correctly initialize pointers to nullptr.

- JSON values that have no class members are ignored
  **Supported as the default behavior.**
- class members that are no pointers have to be present in the JSON, otherwise, an exception should be thrown
  Unfortunately this is not supported. If you want to add the code I will accept a pull request.

**Comment by Loki-Astari** [comment]
Note: Declaring variables like this:

    Test t1, t2, t3, t4;

Is probably not a good idea when you have not define the constructor. The members of these objects are uninitialized. It is just random coincidence that that member `optionalNum` is `nullptr` when you check.

If you explicitly invoke the zero-initialization then you know that the object is zero-ed before use:

    Test t1{}, t2{}, t3{}, t4{};  // Still not good practice to do this on one line.

**Comment by ivohedtke** [comment]
Thanks for the help. When I have time I will come up with a PR, since we need such a feature. But I cannot promise it.

**Comment by Loki-Astari** [comment]
OK. Just pushed a commit that makes this work.
I'll submit to brew over the weekend

**Comment by Loki-Astari** [comment]
The new version is now live with brew.

````
brew install thors-serializer
````
