### ISSUE TITLE
Derived class without new members

### ISSUE THREAD

**Issue by ivohedtke** [Loki-Astari/ThorsSerializer#40]
I implement the webservice for a given API and I am forced to have a derived class with no new members in it (the external API wants that). But `ThorsAnvil_ExpandTrait` expects to give a list of members.

So this code
```c++
struct Derived : public Base {
    ~Derived() override = default;
    ThorsAnvil_PolyMorphicSerializer(Derived);
};

ThorsAnvil_ExpandTrait(Base, Derived);
```

does not compile:

```
error: expected unqualified-id
ThorsAnvil_ExpandTrait(Base, Derived);
^
/usr/local/include/ThorSerialize/Traits.h:277:5: note: expanded from macro 'ThorsAnvil_ExpandTrait'
    ThorsAnvil_MakeTrait_Base(ThorsAnvil_Parent(0, ParentType, DataType, __VA_ARGS__, 1), Parent, 0, DataType, __VA_ARGS__, 1); \
```

**Comment by Loki-Astari** [comment]
Thanks for the error report.
I'll have a look on Sun 2019/Feb/17

**Comment by Loki-Astari** [comment]
OK I have a fix.
It is tested by the new unit test: [DerivedTypeNoNewMembers](https://github.com/Loki-Astari/ThorsSerializer/blob/2af7e76d20c4bf71580de544d8703596a5b636e7/src/Serialize/test/SerializeTest.cpp#L287)

Updates have been pushed to git.
I am submitting a request to brew to update ThorsSerializer. This can take a day. When done I will update and close this error report.

**Comment by Loki-Astari** [comment]
brew pull request started
https://github.com/Homebrew/homebrew-core/pull/37024

**Comment by Loki-Astari** [comment]
New version now installable with homebrew.

**Comment by Loki-Astari** [comment]
Noticed another issue.

**Comment by Loki-Astari** [comment]
OK I have a fix.
It is tested by the new unit test: [DerivedTypeNoNewMembersPolyMorphic](https://github.com/Loki-Astari/ThorsSerializer/blob/34edb4eec2e51b1eb9772276a69674c003622fef/src/Serialize/test/SerializeTest.cpp#L301)

Updates have been pushed to git.
I am submitting a request to brew to update ThorsSerializer. This can take a day. When done I will

**Comment by Loki-Astari** [comment]
New version now installable with homebrew.
https://github.com/Homebrew/homebrew-core/pull/37040
