### ISSUE TITLE
Having trouble installing the library with Homebrew

### ISSUE THREAD

**Issue by isasmarthalo** [Loki-Astari/ThorsSerializer#43]
When I run this command in the terminal `brew install thors-serializer`
I always have this error: 
```
Last 15 lines from /home/mint/.cache/Homebrew/Logs/thors-serializer/02.make:
                       ^~~
Serialize.tpp:231:39: error: template argument 1 is invalid
 struct ConvertPointer<std::unique_ptr<T>>
                                       ^
Serialize.tpp:231:40: error: expected unqualified-id before '>' token
 struct ConvertPointer<std::unique_ptr<T>>
                                        ^~
/tmp/thors-serializer-20190313-23707-r92s0c/build/tools/Makefile:645: recipe for target 'coverage/Serialize.o' failed
make[3]: *** [coverage/Serialize.o] Error 1
/tmp/thors-serializer-20190313-23707-r92s0c/build/tools/Makefile:375: recipe for target 'unit_test' failed
make[2]: *** [unit_test] Error 2
/tmp/thors-serializer-20190313-23707-r92s0c/build/tools/Project.Makefile:47: recipe for target 'Serialize.dir' failed
make[1]: *** [Serialize.dir] Error 2
/tmp/thors-serializer-20190313-23707-r92s0c/build/tools/Project.Makefile:47: recipe for target 'src.dir' failed
make: *** [src.dir] Error 2
```
I tried running the install with gcc-6 which uses c++14 automatically but still get the error.
I also did a bunch of stuff:
updated homebew
downloaded gcc and g++ 6 and making sure the used version was 6.1 and higher
I don't know what I should do 

Thank you

**Comment by Loki-Astari** [comment]
I just update the homebrew package.
When it is accepted it should build correctly.
You can check the [pull request here](https://github.com/Homebrew/homebrew-core/pull/37897) to see if it has been accepted

**Comment by Loki-Astari** [comment]
New version was accepted by brew.
This was the [fix](https://github.com/Loki-Astari/ThorsSerializer/commit/7228aa6e41dd9eaa8e65a2405e7718cb339c671e#diff-4153dd97bc27caa05615e343111eb05c):

**Comment by isasmarthalo** [comment]
Thank you :)
