### ISSUE TITLE
Is "__type" not required to be the first property anymore?

### ISSUE THREAD

**Issue by ivohedtke** [Loki-Astari/ThorsSerializer#47]
The documentation states that "__type" has to be the first property when polymorphic types are used: https://github.com/Loki-Astari/ThorsSerializer/blob/master/doc/full.md#example-3-see-docexample3cpp

I noticed that a partner using the REST webservice we provide uses a JSON client that automatically sorts members and it thinks "__type" should be sorted as "type". Thus, it does not appear as the first property of the JSON anymore. But there is no exception from ThorsSerializer. 

Is it not required any more that it has to be the first property?

**Comment by Loki-Astari** [comment]
I just tried this.  
My tests generate an exception when deserializing **polymorphic** objects.

Can you provide a simple test that reproduces the problem.

Note: If the type is not polymorphic. Then having '__type' as one of the keys will be ignored unless you specify the `ParserInterface::ParseType::Strict` in the constructor for **Parser** you are using.

**Comment by Loki-Astari** [comment]
Closing issue as it seems to work correctly in the tests.
OP has not provided a specific use case that causes failure.

**Comment by ivohedtke** [comment]
Sorry for the late response. This code and the example JSON does not give me an exception.

```c++
#include <iostream>
#include <ThorSerialize/JsonThor.h>
#include <ThorSerialize/SerUtil.h>
#include <ThorSerialize/Traits.h>

struct RegulationsBase {
  std::unique_ptr<int> id { nullptr };
  virtual ~RegulationsBase() = default;
  ThorsAnvil_PolyMorphicSerializer(RegulationsBase);
};
ThorsAnvil_MakeTrait(RegulationsBase, id);

struct DriverRegulations : public RegulationsBase {
  std::unique_ptr<int> beginningOfCalendarWeek { nullptr };
  ~DriverRegulations() override = default;
  ThorsAnvil_PolyMorphicSerializer(DriverRegulations);
};
ThorsAnvil_ExpandTrait(RegulationsBase, DriverRegulations, beginningOfCalendarWeek);


int main() {
  DriverRegulations dr {};
  std::string str = R"(
    {
      "beginningOfCalendarWeek": 5,
      "__type": "DriverRegulations"
    }
  )";
  std::istringstream stream(str);
  stream >> ThorsAnvil::Serialize::jsonImport(dr);

  return 0;
}
```

**Comment by ivohedtke** [comment]
I am also not able to reproduce it. In case it happens again. I will prepare an example.
