### ISSUE TITLE
Issue with ThorsAnvil_MakeEnum

### ISSUE THREAD

**Issue by danielaparker** [Loki-Astari/ThorsSerializer#49]
In `traits.h`, in the macro `ThorsAnvil_MakeEnum`, we have

```c++
static EnumName getValue(std::string const& val, std::string const& msg) \
{                                                               \
    char const* const* values = getValues();                    \
    std::size_t        size   = getSize();                      \
    for (std::size_t loop = 0;loop < size; ++loop)              \
    {                                                           \
        if (val == values[loop]) {                              \
            return static_cast<EnumName>(loop);                 \
        }                                                       \
    }                                                           \
    throw std::runtime_error(msg + " Invalid Enum Value");      \
}                                                               \
```
This looks to me like it will only work for enum types with consecutive values. That is, it will work for your test case,
```c++
enum RGB { Red, Green, Blue };
```
but not for something like
```c++
enum class FloatFormat {scientific = 1,fixed = 2,hex = 4,general = fixed | scientific};
```
Note that in the latter instance,  the default initialized value `FloatFormat()` is a valid enum value even though, being 0, there is no name for it in the list, and the named values are not consecutive.

Instead of generating an array of `# member`, I would suggest generating an array of `{EnumName::member, # member}` pairs. Then `getValue` can search for the name and return the corresponding `EnumName`. I think you also need a fallback if there is no name for the default initialized value `EnumName()`, perhaps associating it with an empty string, or some other convention.

Also consider something like

```c++
enum class ErrorCode {Error1 = 1, Error2};
```

where `ErrorCode()` represents success. The standard library `std::errc` uses this convention. In this case you would want to be able to serialize/deserialize
```c++
ErrorCode ec = ErrorCode();
```

Best regards,
Daniel

**Comment by Loki-Astari** [comment]
@danielaparker That's a good suggestion.

I can do it this weekend. But I am more than willing to accept a pull request. You even have the perfect test case to add to the unit tests.

**Comment by Loki-Astari** [comment]
Update:  https://github.com/Loki-Astari/ThorsSerializer/commit/6ac1586f6e56133ffbad2aa9e747de26c765b6c1 . 
Homebrew pull-request: https://github.com/Homebrew/homebrew-core/pull/41680
