### ISSUE TITLE
Add support to change the json property names when serializing/deserializing 

### ISSUE THREAD

**Issue by fabioalexsander** [Loki-Astari/ThorsSerializer#56]
Is it possible to have one field in the class, but different names for it during serialization/deserialization?

Something like this:

public class Videogame
{
    private:
       
      [JsonProperty("name")]
       string Name;

       [JsonProperty("release_date")]
       private DateTime ReleaseDate;
}

Videogame starcraft = new Videogame
{
    Name = "Starcraft",
    ReleaseDate = new DateTime(1998, 1, 1)
};

string json = ThorsAnvil::Serialize::jsonExport(starcraft);

Console.WriteLine(json);
// {
//   "name": "Starcraft",
//   "release_date": "1998-01-01T00:00:00"
// }

**Comment by qiujiangkun** [comment]
You can do it by adding your traits. Actually they are poorly documented(but still mentioned on another site) but the framework is not hard to understand while not documented at all

**Comment by Loki-Astari** [comment]
Done:
Use the macros:

* ThorsAnvil_MakeTraitName_Override
* ThorsAnvil_Template_MakeTraitNameOverride

Check Examples here: https://github.com/Loki-Astari/ThorsSerializer/blob/master/src/Serialize/test/OverrideIdentiferToKeyMapTest.cpp
