### ISSUE TITLE
No compile enum with 8 and more element

### ISSUE THREAD

**Issue by deevroman** [Loki-Astari/ThorsSerializer#63]
```
#include "../../external/ThorsSerializer/ThorSerialize/Traits.h"

enum TypeToken {
    KEYWORD, NAME, STRING,
    NUMBER, BEGIN_LINE, BEGIN_BLOCK, OPERATOR,
    ENDMARKER
};


ThorsAnvil_MakeEnum(TypeToken, KEYWORD, NAME, STRING,
                    NUMBER, BEGIN_LINE, BEGIN_BLOCK, OPERATOR, ENDMARKER);

int main() {
    return 0;
}
```

`g++ --std=c++17 main.cpp`

```
main.cpp:92:1: error: invalid digit '8' in octal constant
ThorsAnvil_MakeEnum(TypeToken, KEYWORD, NAME, STRING,
^
./../../external/ThorsSerializer/ThorSerialize/Traits.h:304:20: note: expanded from macro 'ThorsAnvil_MakeEnum'
            return NUM_ARGS(__VA_ARGS__, 1);                            \
                   ^
./../../external/ThorsSerializer/ThorSerialize/Traits.h:34:199: note: expanded from macro 'NUM_ARGS'
  ...40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 09, 08, 07, 06, 05, 04, 03, 02, 01, 00, Ignore)
                                                                                                                                      ^
1 error generated.
```

**Environment:**
 - OS: Mac OS 10.15.4
> uname -a
Darwin RD.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

 - Compiler and Version
> g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by Loki-Astari** [comment]
That bug has already been found and fixed.
Let me just look up the tag it was fixed with.

Did you install with `brew`?
Easiest way to get the latest version is: `brew upgrade thors-serializer`

**Comment by Loki-Astari** [comment]
Yes fixed in pull request 58:
https://github.com/Loki-Astari/ThorsSerializer/pull/58

**Comment by Loki-Astari** [comment]
PS.
If you install via brew you don't need this header:

````
    #include "../../external/ThorsSerializer/ThorSerialize/Traits.h"

    // Can now simplify to:
    #include <ThorSerialize/Traits.h>
````

**Comment by deevroman** [comment]
Yeah, really, I had old sources. Installation via brew is not good for me because I need the project to be built on more than just mac os, and without installing anything on the system. Thank you for the answer.

**Comment by Loki-Astari** [comment]
Glad I could help.
Is this s a public project I can look at?

**Comment by deevroman** [comment]
So far, it's a private project. It's a school project.
