### ISSUE TITLE
Std:array not working on header only version

### ISSUE THREAD

**Issue by gladijos** [Loki-Astari/ThorsSerializer#65]
**Describe the bug**
> A minimal compilable example of that features the bug.

```
#include <fstream>
#include "ThorSerialize/JsonThor.h"
#include "ThorSerialize/SerUtil.h"

struct TestClass
{
  std::array<uint8_t, 16> testField;
};

ThorsAnvil_MakeTrait(TestClass, testField);

using ThorsAnvil::Serialize::jsonExport;
using ThorsAnvil::Serialize::jsonImport;
int main(int argc, char* argv[])
{
  std::fstream fileStream;
  TestClass entity;
  fileStream >> jsonImport(entity);
  fileStream << jsonExport(entity);
  return 0;
}
```

> A description of how to build and run the code. I use header-only version

    g++ -std=c++14 -I/usr/local/include  main.cpp

**Expected behavior**
> compile OK

**Environment:**
 - OS:
> uname -a
Linux gladijos-desktop 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 - Compiler and Version
> g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.

**Additional context**
> I got compile-time error

> base-path-to-3rd-party-libraries/ThorsSerializer/ThorSerialize/Serialize.tpp: In instantiation of ‘class ThorsAnvil::Serialize::SerializerForBlock<(ThorsAnvil::Serialize::TraitType)0, unsigned char>’:
> base-path-to-3rd-party-libraries/ThorsSerializer/ThorSerialize/Serialize.tpp:807:48:   required from ‘void ThorsAnvil::Serialize::Serializer::print(const T&) [with T = unsigned char]’
> base-path-to-3rd-party-libraries/ThorsSerializer/ThorSerialize/SerUtil.h:105:13:   required from ‘void ThorsAnvil::Serialize::PutValueType<V, type>::putValue(const V&) [with V = unsigned char; ThorsAnvil::Serialize::TraitType type = (ThorsAnvil::Serialize::TraitType)0]’
> base-path-to-3rd-party-libraries/ThorsSerializer/ThorSerialize/SerUtil.h:190:17:   required from ‘void ThorsAnvil::Serialize::ContainerMemberExtractorEmplacer<C, V>::operator()(ThorsAnvil::Serialize::PrinterInterface&, const C&) const [with C = std::array<unsigned char, 16>; V = unsigned char]’
> base-path-to-3rd-party-libraries/ThorsSerializer/ThorSerialize/Serialize.tpp:801:11:   required from ‘void ThorsAnvil::Serialize::Serializer::printMembers(const T&, Action) [with T = std::array<unsigned char, 16>; Action = ThorsAnvil::Serialize::ContainerMemberExtractorEmplacer<std::array<unsigned char, 16>, unsigned char>]’
> base-path-to-3rd-party-libraries/ThorsSerializer/ThorSerialize/Serialize.tpp:839:5:   required from ‘void ThorsAnvil::Serialize::Serializer::printObjectMembers(const T&) [with T = std::array<unsigned char, 16>]’
> base-path-to-3rd-party-libraries/ThorsSerializer/ThorSerialize/Serialize.tpp:729:13:   [ skipping 5 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
> base-path-to-3rd-party-libraries/ThorsSerializer/ThorSerialize/Serialize.tpp:795:5:   required from ‘void ThorsAnvil::Serialize::Serializer::printMembers(const T&, const std::tuple<_Elements ...>&) [with T = TestClass; Members = {std::pair<const char*, std::array<unsigned char, 16> TestClass::*>}]’
> base-path-to-3rd-party-libraries/ThorsSerializer/ThorSerialize/Serialize.tpp:839:5:   required from ‘void ThorsAnvil::Serialize::Serializer::printObjectMembers(const T&) [with T = TestClass]’
> base-path-to-3rd-party-libraries/ThorsSerializer/ThorSerialize/Serialize.tpp:577:13:   required from ‘void ThorsAnvil::Serialize::SerializerForBlock<traitType, T>::printMembers() [with ThorsAnvil::Serialize::TraitType traitType = (ThorsAnvil::Serialize::TraitType)3; T = TestClass]’
> base-path-to-3rd-party-libraries/ThorsSerializer/ThorSerialize/Serialize.tpp:808:5:   required from ‘void ThorsAnvil::Serialize::Serializer::print(const T&) [with T = TestClass]’
> base-path-to-3rd-party-libraries/ThorsSerializer/ThorSerialize/Exporter.h:35:17:   required from ‘std::ostream& ThorsAnvil::Serialize::operator<<(std::ostream&, const ThorsAnvil::Serialize::Exporter<ThorsAnvil::Serialize::Json, TestClass>&)’
> ./main.cpp:22:38:   required from here
> base-path-to-3rd-party-libraries/ThorsSerializer/ThorSerialize/Serialize.tpp:555:5: error: static assertion failed: Invalid Serialize Trait

**Comment by gladijos** [comment]
Possible this issue come from using uint8_t type, with int type compiles fine

**Comment by ripe909** [comment]
There is no support for char or uint8_t, so that is probably the issue.  I did add some customizations to my code that support uint8_t as an int and the array of uint8_t does work.

**Comment by Loki-Astari** [comment]
The supported basic types are defined here:

https://github.com/Loki-Astari/ThorsSerializer/blob/master/src/Serialize/Traits.h#L436

Not sure how to support type aliases.
Or if using traits on type alieases would work consistently that is something I would need to test a bit.

**Comment by ripe909** [comment]
Since I would never use char, only uint8, I added all of the appropriate functions to treat it like an int. It worked like any other type, except I had to cast it when putting it into the stream to make sure it wasn't treated as a char in the Printer override:

```
HEADER_ONLY_INCLUDE void JsonPrinter::addValue(uint8_t value)
{ output << PrefixValue(config.characteristics, state.size(), state.back()) << (unsigned int) value;}
```

**Comment by Loki-Astari** [comment]
@ripe909 The only issue here are:

1. `uint8` is not a C++ type. 
2. Though `uint8_t` is but only in the `std` namespace (so `std::uint8_t`).

I am more than happy to accept a pull request with these modifications (and appropriate unit tests).

**Comment by ripe909** [comment]
I will try and create a clean PR.  

It would probably make more sense to use char type rather than the uint8_t alias. 
I just use uint8_t to make the intention clear, but it is just an alias for unsigned char in my toolchain.

Maybe a directive that must be set to enable the use of chars as ints would make it clearer?
