### ISSUE TITLE
my compile problem of example1

### ISSUE THREAD

**Issue by z8002** [Loki-Astari/ThorsSerializer#70]
sorry if it is too simple actually its not issue im looking for help. i just started to compile an build c++ programs. 
my question is :  i downloaded the thorserialize.zip  and unzip in my ubuntu.
i folders i want to just run the example1 code with 
`	g++ -l/home/suser/Desktop/ThorsSerializer/ThorSerialize example1.o -o example1.cpp `
console code but it gives me 
_example1.cpp:1:10: fatal error: ThorSerialize/Traits.h: No such file or directory_

what did i wrong ?? can you explain to me

**Comment by Loki-Astari** [comment]
Where did you get the zip?

Easy way to install on linux is via brew
