### ISSUE TITLE
Tags with header only

### ISSUE THREAD

**Issue by DraTeots** [Loki-Astari/ThorsSerializer#74]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when it is said there should be a single header file and I can't find it. Even more frustrating, when there is no CMake but old Makefiles (no complains to developers, just our system is CMake centric, so it is our problem, but still...)

**Describe the solution you'd like**
Just make those header only version easy to download and attach to tags

**Describe alternatives you've considered**
Use another library

**Comment by DraTeots** [comment]
Ok, there where no claims about single header. Only "header only".

**Comment by Loki-Astari** [comment]
The old `Makefile` stuff works everywhere (unlike CMake), no extra stuff required.
Once it is built you can use it from you CMake files :-)

To use the header only version.

````
> git clone --single-branch --branch header-only https://github.com/Loki-Astari/ThorsSerializer.git
  /PATH/TO/WHERE/I/WANT/TO/INSTALL/ThorsSerializer

 g++ -I /PATH/TO/WHERE/I/WANT/TO/INSTALL/ThorsSerializer MyFile.cpp
````

**Comment by DraTeots** [comment]
"Once it is built you can use it from you CMake files :-)"

Do you generate thors-serializerConfig.cmake and  thors-serializer.cmake files?

**Comment by Loki-Astari** [comment]
No. But they should be trival to do if you know CMake (which I don't).

The only things you need are:

* where the header files are installed: `-I<ThorHeaderDir>`
* where the libraries are installed: `-L<ThorLibraryDir>`
* The name of the library; `-l<libraryName>`

Default values are:
````
ThorHeaderDir  => /usr/local/include
ThorLibraryDir  => /usr/local/lib
libraryName     => ThorSerialize17
````

**Comment by Loki-Astari** [comment]
If you create one I will add to the project for future developers to use.

**Comment by Loki-Astari** [comment]
According to this page: http://doc.aldebaran.com/qibuild/advanced/guide/cmake/writing_a_config_cmake.html

It should look like this:

````
clean(ThorsSerializer)
fpath(ThorsSerializer ThorSerialize/JsonThor.h)
flib(ThorsSerializer ThorSerialize17)
export_lib(ThorsSerializer)
````

**Comment by Loki-Astari** [comment]
Massively cleaned up the header only version.
