### ISSUE TITLE
Why there is no CMAKE support?

### ISSUE THREAD

**Issue by VladlenPopolitov** [Loki-Astari/ThorsSerializer#82]
**Is your feature request related to a problem? Please describe.**
Your library looks very interesting and better than similar solutions. It would be much easier to integrate it into the new projects, if it had cmake support. Now cmake made very simple inclusion of the cmake projects into cmake project (find_package or add_subdirectory). Also cmake makes good configuration on all OS , even where configure does not work.

**Describe the solution you'd like**
Make CMakeLists.txt files to generate include files, tests, documentation and examples. It is not hard work, if 'configure' exists and work: create new txt files, copy-past file names.

**Comment by Loki-Astari** [comment]
You can include make files directly within your make project.

https://stackoverflow.com/q/44501921/14065

**Comment by VladlenPopolitov** [comment]
Sorry to say, but it does not always working. For example, in Windows (MSVC) make is not used. It is why cmake is invented - to create makefiles or other project files for all development platforms. Your library could have more opportunities.

**Comment by Loki-Astari** [comment]
Make works on Windows.

I have tested and built on Windows successfully.

If you really need an easy way then use the header only version then no make or cmake are required.

But I would seriously recommend learning to use make as it is much more sophisticated and versatile than cmake.

**Comment by VladlenPopolitov** [comment]
make is not used in MSVC environment, MSVC uses other tools to build projects. I would seriously recommend learning to use cmake, as it absolutely different tools for other purposes comparing to make (cmake is the maker of Makefiles, make is the executor of Makefiles). I do not have more question, it is your project. 
I am with `make` since 1992 fyi.

**Comment by Loki-Astari** [comment]
That's why there is a header only version 😉

git clone --single-branch --branch header-only https://github.com/Loki-Astari/ThorsSerializer.git

Now it builds on MSVC
